/* eslint-disable global-require */
import Media from '~/models/Media';

const medias: Media[] = [
  {
    id: 1,
    title: 'The Witcher',
    art: require('~/assets/medias/witcher/art.jpg').default,
    titleArt: require('~/assets/medias/witcher/titleArt.webp').default,
    file: require('~/assets/medias/witcher/media.mp4').default,
    synopsis: `Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.`,
    rating: 16,
    duration: '1 Season',
    tags: ['Exciting'],
  },
  {
    id: 2,
    title: '6 Underground',
    art: require('~/assets/medias/6underground/art.jpg').default,
    titleArt: require('~/assets/medias/6underground/titleArt.webp').default,
    file: require('~/assets/medias/6underground/media.mp4').default,
    synopsis: `After faking his death, a tech billionaire recruits a team of international operatives for a bold and bloody mission to take down a brutal dictator.`,
    rating: 18,
    duration: '2h 8m',
    tags: ['Adrenaline Rush', 'Slick', 'Violent'],
  },
  {
    id: 3,
    title: 'Bates Motel',
    art: require('~/assets/medias/bates-motel/art.jpg').default,
    titleArt: require('~/assets/medias/bates-motel/titleArt.webp').default,
    file: require('~/assets/medias/bates-motel/media.mp4').default,
    synopsis: `When his father dies, Norman Bates and his mother open a hotel. But Norman's precarious mental state drives them down a dark and violent path.`,
    rating: 16,
    duration: '5 Seasons',
    tags: ['Ominuous', 'Psychological', 'Suspenseful'],
  },
  {
    id: 4,
    title: 'Black Spot',
    art: require('~/assets/medias/black-spot/art.jpg').default,
    titleArt: require('~/assets/medias/black-spot/titleArt.webp').default,
    file: require('~/assets/medias/black-spot/media.mp4').default,
    synopsis: `Villefranche is a small town with no phone reception on the edge of a mysterious forest. The number of inhabitants is dwindling but there's a sharp rise in crime. Police inspector Laurene, once the victim of a crime herself, keeps on discovering fresh corpses.`,
    rating: 16,
    duration: '2 Seasons',
    tags: ['Dark', 'Suspenseful'],
  },
  {
    id: 5,
    title: 'Brooklyn Nine-Nine',
    art: require('~/assets/medias/brooklyn99/art.jpg').default,
    titleArt: require('~/assets/medias/brooklyn99/titleArt.webp').default,
    file: require('~/assets/medias/brooklyn99/media.mp4').default,
    synopsis: `A ensemble comedy following the lives of an eclectic group of detectives in a New York precinct, including one slacker who is forced to shape up when he gets a new boss.`,
    rating: 16,
    duration: '5 Seasons',
    tags: ['Goofy'],
  },
  {
    id: 6,
    title: 'Death Note',
    art: require('~/assets/medias/death-note/art.jpg').default,
    titleArt: require('~/assets/medias/death-note/titleArt.webp').default,
    file: require('~/assets/medias/death-note/media.mp4').default,
    synopsis: `A high school student named Light Turner discovers a mysterious notebook that has the power to kill anyone whose name is written within its pages, and launches a secret crusade to rid the world of criminals.`,
    rating: 16,
    duration: '1h 40m',
    tags: ['Mind-Bending', 'Scary'],
  },
  {
    id: 7,
    title: 'Dracula',
    art: require('~/assets/medias/dracula/art.jpg').default,
    titleArt: require('~/assets/medias/dracula/titleArt.webp').default,
    file: require('~/assets/medias/dracula/media.mp4').default,
    synopsis: `The Count Dracula legend transforms with new tales that flesh out the vampire's gory crimes -- and bring his vulnerability into the light.`,
    rating: 16,
    duration: '1 Season',
    tags: ['Scary', 'Suspenseful'],
  },
  {
    id: 8,
    title: 'The End of the F***ing World',
    art: require('~/assets/medias/end-of-the-world/art.jpg').default,
    titleArt: require('~/assets/medias/end-of-the-world/titleArt.webp').default,
    file: require('~/assets/medias/end-of-the-world/media.mp4').default,
    synopsis: `Bored with killing animals, 17-year-old James is busy plotting his first real murder when brash new girl Alyssa catches him off guard at school.`,
    rating: 16,
    duration: '2 Seasons',
    tags: ['Deadpan', 'Offbeat'],
  },
  {
    id: 9,
    title: 'Good Girls',
    art: require('~/assets/medias/good-girls/art.jpg').default,
    titleArt: require('~/assets/medias/good-girls/titleArt.webp').default,
    file: require('~/assets/medias/good-girls/media.mp4').default,
    synopsis: `As Beth, Ruby and Annie face personal and financial crises, they decide to team up and take back their lives -- by robbing their local grocery store.`,
    rating: 14,
    duration: '2 Seasons',
    tags: ['Witty', 'Irreverent'],
  },
  {
    id: 10,
    title: 'Hannibal',
    art: require('~/assets/medias/hannibal/art.jpg').default,
    titleArt: require('~/assets/medias/hannibal/titleArt.webp').default,
    file: require('~/assets/medias/hannibal/media.mp4').default,
    synopsis: `This drama series focuses on the early years of the relationship between FBI criminal profiler Will Graham and homicidal cannibal Dr. Hannibal Lecter.`,
    rating: 18,
    duration: '3 Seasons',
    tags: ['Gore', 'Psychological', 'Violent'],
  },
  {
    id: 11,
    title: 'The Haunting of Hill House',
    art: require('~/assets/medias/hill-house/art.jpg').default,
    titleArt: require('~/assets/medias/hill-house/titleArt.webp').default,
    file: require('~/assets/medias/hill-house/media.mp4').default,
    synopsis: `While investigating a ghost story for his latest novel, a skeptical Steven receives a call from his sister that triggers a chain of fateful events.`,
    rating: 16,
    duration: '1 Season',
    tags: ['Chilling', 'Scary'],
  },
  {
    id: 12,
    title: 'The I-Land',
    art: require('~/assets/medias/i-land/art.jpg').default,
    titleArt: require('~/assets/medias/i-land/titleArt.webp').default,
    file: require('~/assets/medias/i-land/media.mp4').default,
    synopsis: `Wiped clean of memories and thrown together, a group of strangers fight to survive harsh realities -- and the island that traps them.`,
    rating: 16,
    duration: '1 Season',
    tags: ['Mind-Bending', 'Dystopian', 'Ominous'],
  },
  {
    id: 13,
    title: 'Messiah',
    art: require('~/assets/medias/messiah/art.jpg').default,
    titleArt: require('~/assets/medias/messiah/titleArt.webp').default,
    file: require('~/assets/medias/messiah/media.mp4').default,
    synopsis: `A wary CIA officer investigates a charismatic man who sparks a spiritual movement and stirs political unrest. A fictional story not based on true events.`,
    rating: 16,
    duration: '1 Season',
    tags: ['Provocative', 'Intimate', 'Emotional'],
  },
  {
    id: 14,
    title: 'Mindhunter',
    art: require('~/assets/medias/mindhunter/art.jpg').default,
    titleArt: require('~/assets/medias/mindhunter/titleArt.webp').default,
    file: require('~/assets/medias/mindhunter/media.mp4').default,
    synopsis: `In 1977, frustrated FBI hostage negotiator Holden Ford finds an unlikely ally in veteran agent Bill Tench and begins studying a new class of murderer.`,
    rating: 16,
    duration: '2 Seasons',
    tags: ['Chilling', 'Scary'],
  },
  {
    id: 15,
    title: 'Ozark',
    art: require('~/assets/medias/ozark/art.jpg').default,
    titleArt: require('~/assets/medias/ozark/titleArt.webp').default,
    file: require('~/assets/medias/ozark/media.mp4').default,
    synopsis: `A Chicago-based financial advisor secretly relocates his family to the Missouri Ozarks when his dealings with a drug cartel go awry.`,
    rating: 16,
    duration: '2 Seasons',
    tags: ['Ominous', 'Dark'],
  },
  {
    id: 16,
    title: 'Riverdale',
    art: require('~/assets/medias/riverdale/art.jpg').default,
    titleArt: require('~/assets/medias/riverdale/titleArt.webp').default,
    file: require('~/assets/medias/riverdale/media.mp4').default,
    synopsis: `A subversive take on Archie and his friends, exploring small town life, the darkness and weirdness bubbling beneath Riverdale's wholesome facade.`,
    rating: 16,
    duration: '3 Seasons',
    tags: ['Offbeat', 'Dark'],
  },
  {
    id: 17,
    title: 'Safe',
    art: require('~/assets/medias/safe/art.jpg').default,
    titleArt: require('~/assets/medias/safe/titleArt.webp').default,
    file: require('~/assets/medias/safe/media.mp4').default,
    synopsis: `After his teenage daughter goes missing, a widowed surgeon in an affluent neighborhood begins unearthing dark secrets about the people closest to him.`,
    rating: 16,
    duration: '1 Season',
    tags: ['Slow Burn', 'Gritty', 'Suspenseful'],
  },
  {
    id: 18,
    title: 'Sense8',
    art: require('~/assets/medias/sense8/art.jpg').default,
    titleArt: require('~/assets/medias/sense8/titleArt.webp').default,
    file: require('~/assets/medias/sense8/media.mp4').default,
    synopsis: `A group of people around the world are suddenly linked mentally, and must find a way to survive being hunted by those who see them as a threat to the world's order.`,
    rating: 18,
    duration: '2 Seasons',
    tags: ['Mind-Bending', 'Dark'],
  },
  {
    id: 19,
    title: 'Shadowhunters',
    art: require('~/assets/medias/shadow-hunters/art.jpg').default,
    titleArt: require('~/assets/medias/shadow-hunters/titleArt.webp').default,
    file: require('~/assets/medias/shadow-hunters/media.mp4').default,
    synopsis: `Clary Fray discovers on her 18th birthday that she comes from a long line of shadowhunters, being that are half angel and half human who protect the world by hunting demons.`,
    rating: 14,
    duration: '4 Seasons',
    tags: [],
  },
  {
    id: 20,
    title: 'Stranger Things',
    art: require('~/assets/medias/stranger-things/art.jpg').default,
    titleArt: require('~/assets/medias/stranger-things/titleArt.webp').default,
    file: require('~/assets/medias/stranger-things/media.mp4').default,
    synopsis: `An innocent night playing Dungeons & Dragons takes a tragic turn for a group of friends in Hawkins Indiana when Will Byers disappears...seemingly into thin air. The year is 1983 and this small town is abuzz with conspiracy theories behind the missing boy's circumstances. As friends, family and local police search for answers behind his disappearance they are drawn into an extraordinary mystery involving top-secret government experiments, terrifying supernatural forces and the discovery of one very strange little girl.`,
    rating: 16,
    duration: '2 Seasons',
    tags: ['Ominous', 'Scary'],
  },
  {
    id: 21,
    title: 'The 100',
    art: require('~/assets/medias/the100/art.jpg').default,
    titleArt: require('~/assets/medias/the100/titleArt.webp').default,
    file: require('~/assets/medias/the100/media.mp4').default,
    synopsis: `Set ninety-seven years after a nuclear war has destroyed civilization, when a spaceship housing humanity's lone survivors sends one hundred juvenile delinquents back to Earth, in hopes of possibly re-populating the planet.`,
    rating: 14,
    duration: '5 Seasons',
    tags: ['Violent'],
  },
  {
    id: 22,
    title: 'The Society',
    art: require('~/assets/medias/the-society/art.jpg').default,
    titleArt: require('~/assets/medias/the-society/titleArt.webp').default,
    file: require('~/assets/medias/the-society/media.mp4').default,
    synopsis: `After their class trip is cut short, students at West Ham High School return home to discover their town completely empty.`,
    rating: 16,
    duration: '1 Season',
    tags: ['Suspenseful'],
  },
  {
    id: 23,
    title: 'The Umbrella Academy',
    art: require('~/assets/medias/the-umbrella/art.jpg').default,
    titleArt: require('~/assets/medias/the-umbrella/titleArt.webp').default,
    file: require('~/assets/medias/the-umbrella/media.mp4').default,
    synopsis: `Reunited by their father's death, estranged siblings with extraordinary powers uncover shocking family secrets—and a looming threat to humanity.`,
    rating: 16,
    duration: '1 Season',
    tags: ['Mind-Bending', 'Offbeat'],
  },
];

export default medias;
